services:
  - type: web
    name: mathgen
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 180